name: 16bml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=2.121
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cpuonly=2.0
  - cryptography=39.0.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - flatbuffers=23.5.26
  - fonttools=4.49.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-auth=2.28.1
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.9.0
  - hdf5=1.12.1
  - hpack=4.0.0
  - httpcore=1.0.4
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.6
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2024.0.0
  - ipykernel=6.29.2
  - ipython=8.22.1
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.17
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.1.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.3
  - jupyterlab_widgets=3.0.10
  - keras=2.10.0
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.1.2
  - libdeflate=1.17
  - libffi=3.4.2
  - libglib=2.78.4
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.5
  - libpng=1.6.43
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libuv=1.47.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.5.2
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.16.1
  - nbconvert-core=7.16.1
  - nbconvert-pandoc=7.16.1
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.1.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - oauthlib=3.2.2
  - opencv=4.6.0
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.2.1
  - pandoc=3.1.12.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - protobuf=3.20.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-flatbuffers=23.5.26
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.2.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywin32=306
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - qtwebkit=5.212
  - re2=2022.06.01
  - referencing=0.33.0
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - rsa=4.9
  - scipy=1.12.0
  - send2trash=1.8.2
  - setuptools=69.1.1
  - sip=6.5.1
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.1
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.4.0
  - terminado=0.18.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.2.1
  - torchvision=0.17.1
  - tornado=6.4
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - opencv-contrib-python==4.9.0.80
